# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-08 15:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_service', '0002_auto_20180206_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreuser',
            name='birth_date',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
            preserve_default=False,
        ),
    ]
