# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-16 08:37
from __future__ import unicode_literals

import authentication_service.models
from django.db import migrations, models
import project.settings


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_service', '0003_auto_20180710_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=project.settings.MediaStorage(), upload_to=authentication_service.models.user_avatar_path),
        ),
    ]
