# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-07 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_service', '0004_auto_20180306_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='id',
        ),
        migrations.AddField(
            model_name='coreuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(default='a', max_length=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
