# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_service', '0005_auto_20180307_1212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coreuser',
            options={},
        ),
        migrations.AlterField(
            model_name='coreuser',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication_service.Country', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='coreuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other')], max_length=10, null=True, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='usersecurityquestion',
            name='answer',
            field=models.TextField(verbose_name='answer'),
        ),
        migrations.AddIndex(
            model_name='coreuser',
            index=models.Index(fields=['email'], name='authenticat_email_a52eb3_idx'),
        ),
        migrations.AddIndex(
            model_name='coreuser',
            index=models.Index(fields=['date_joined'], name='authenticat_date_jo_188bff_idx'),
        ),
        migrations.AddIndex(
            model_name='coreuser',
            index=models.Index(fields=['gender'], name='authenticat_gender_277866_idx'),
        ),
        migrations.AddIndex(
            model_name='coreuser',
            index=models.Index(fields=['last_login'], name='authenticat_last_lo_f8ef1c_idx'),
        ),
        migrations.AddIndex(
            model_name='coreuser',
            index=models.Index(fields=['updated_at'], name='authenticat_updated_766884_idx'),
        ),
    ]
