# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 09:22
from __future__ import unicode_literals

from django.db import migrations
import partial_index


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_service', '0006_auto_20180423_0835'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='coreuser',
            index=partial_index.PartialIndex(fields=['is_active'], name='authenticat_is_acti_7ff3d3_partial', unique=False, where='', where_postgresql='is_active = false', where_sqlite=''),
        ),
        migrations.AddIndex(
            model_name='coreuser',
            index=partial_index.PartialIndex(fields=['email_verified'], name='authenticat_email_v_74d3e8_partial', unique=False, where='', where_postgresql='email_verified = true', where_sqlite=''),
        ),
        migrations.AddIndex(
            model_name='coreuser',
            index=partial_index.PartialIndex(fields=['msisdn_verified'], name='authenticat_msisdn__e2202e_partial', unique=False, where='', where_postgresql='msisdn_verified = true', where_sqlite=''),
        ),
    ]
