# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-02 09:05
from __future__ import unicode_literals

import authentication_service.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_service', '0006_auto_20180424_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreuser',
            name='q',
            field=authentication_service.models.AutoQueryField(null=True),
        ),
    ]
