# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-15 09:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_service', '0008_auto_20180502_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.IntegerField()),
                ('consented_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='usersite',
            index=models.Index(fields=['site_id'], name='authenticat_site_id_45d2c8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usersite',
            unique_together=set([('user', 'site_id')]),
        ),
    ]
