# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 12:50
from __future__ import unicode_literals

import authentication_service.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_service', '0008_auto_20180423_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreuser',
            name='q',
            field=authentication_service.models.AutoQueryField(default=None),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='coreuser',
            index=authentication_service.models.TrigramIndex(fields=['q'], name='authenticat_q_2fcb4b_gin'),
        ),
    ]
