# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-15 13:23
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_service', '0009_auto_20180515_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreuser',
            name='migration_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
