sudo: required
cache: pip
language: python
python: "3.6"

services:
    - docker
    - redis-server

env:
  - TOXENV=django111

install:
  - pip install tox

script: tox

after_success:
  - export REPO=dockerhubowner/authentication-service
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH_CLEAN ; fi`
  - export build -t $REPO:$TAG .

