sudo: required
cache: pip
language: python

services:
    - docker

env:
  - TOXENV=django111

install:
  - pip install tox

script: tox

after_success:
  - export REPO=dockerhubowner/core-authentication-service
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH_CLEAN ; fi`
  - export build -t $REPO:$TAG .

