sudo: required
cache: pip
language: python
python:
- '3.6'
env:
  matrix:
  - TOXENV=django111
  - global:
    - secure: kcAJD0F3XWLdCYuab50X16ENAYNt3O9qcAmSAVQiYbrLFyOeW3sRlgkymYiwQpFYyIiThL2IATUM/eTImHHpQg44PRb7MGQO/e9Z7lo4gEGdNLHuLltWqm+q+z8snQHLsuNSN9EJanELPZUjtwub1SiJiPO8vMDCdg7/Zu6CdPBmwyS04nZ6F16VrQVjeb/cRjOv5cDlELD6CMmFW/CvQoOy+1JwlfFjLTWufhB+ZlisXQrsUt5tbUbmbu1rEWrfGo7sVzPZs6b7nGgC9pBNPZd9oZWglvfyoWwOkxQluFqCmXcjTphP61a/2jdAqrP1ABaGEk76gN2Vb48B46uoMTJhutBxzoezKyienNOm6dwT8BelFgoQzuYa8aoii3Pk1w/3nGS800pLGKJsd9wQ01LVPrYY6kXuTwc4iW5lLo9vFpb+LzfKAxEw4kWyWQElYl4E817K8JIqdj9RiMEEsjNBy4CbswvUCqsPIbK53yQ6uulJVXu8PTUhV3v3gbj/pYEVqLODetRkxS7rFb7hoG2isnP15yRsbi+ytNcwZfFeA/fcX8C0Mlc88nBATNFF7XbO+Irs4mEN63YqC3zZBesFzkH/DffwjPW+lcsXJg9kCsJeCFiZo/WR5+ayNQZjULjjHbERi1mz8o0KKXj7H/EggMr6kKIyd3amx/WGbGk=
    - secure: r6rofPXWsB+7afzdwtJ6fjwWX+NMxD+xJliiWUwdRqnAPyWnzlFisl4SnNYzbFjpZoo13BnFOFYDPm3Tl7GzBie0RgEjLnufH40YFnzkby+2T23sMpF777KOslIeB+Q1UXL86gZDZ9YinenA675eugntdPW2CdGJh1QPJPNtNC+lP4HXOYkYI/ZBrenLJvDKts0Cq52tQC1QqnfRyIYFPmyAnQvXuVtj+Tvw0QaqnfxtBYzYwZBabeIIK4MkUjabnlxqQNhlEkkW2l3Ois8x4sginFQZqf1ORJ8K/Z2x5wB8MITuMn+Op+coEPbZJeLZaxz5D5rjYSDJ41wGJGwfP4vUgg4NjD93FHdJd+gTM4j62Wk9lJSVl8iK8jn9qqBSark4bp6ZmNRqG4sLdHBYqBUJW1LMXn85BsPOT4dBB7x4oYGk4DBlBXsHF4yp7yJN1nMxGI0s0YCsgavV/zsNr8jHO+b8TAFbZ5lciIKOtWtXc3CJNikRkaeLsPK3cTRSsAVnSoEde6Z4M7oAf2Y5uLocJW1FhHtfawpsVtdib2lUmdsff8auzUClLofjdmZqS3nBkco9BUfWBW4KShxZwuuyyGJ285eLkCs3wYOG75iXxzIhAmINdvtS7BUL+lxGZ3AseT2s82f8pMUxP0aP59dibmWxJ+LWapQYg7f89nY=

services:
- docker
- redis-server
- postgresql
install:
- pip install tox coveralls
script: tox
after_success:
- coveralls
deploy:
- provider: script
  script: bash ./scripts/docker_push.sh
  on:
    branch: feature/GE-850
- provider: script
  script: bash ./scripts/docker_push.sh
  on:
    branch: master
- provider: script
  script: bash ./scripts/docker_push.sh
  on:
    branch: develop
- provider: script
  script: bash ./scripts/docker_push.sh
  on:
    all_branches: true
    condition: "${TRAVIS_BRANCH} =~ ^release.*$"
