# coding: utf-8

"""
    Access Control API

    # The Access Control API  ## Overview The Access Control API is an API exposed to other core components. It uses an API Key in an HTTP header to perform authentication and authorisation.  Most of the API calls facilitates CRUD of the entities defined in the Access Control component. Others calls allows the retrieval of information in a form that is convenient for other components (most notably the Management Layer) to consume.   # noqa: E501

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class RoleResourcePermissionCreate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'role_id': 'int',
        'resource_id': 'int',
        'permission_id': 'int'
    }

    attribute_map = {
        'role_id': 'role_id',
        'resource_id': 'resource_id',
        'permission_id': 'permission_id'
    }

    def __init__(self, role_id=None, resource_id=None, permission_id=None):  # noqa: E501
        """RoleResourcePermissionCreate - a model defined in Swagger"""  # noqa: E501

        self._role_id = None
        self._resource_id = None
        self._permission_id = None
        self.discriminator = None

        self.role_id = role_id
        self.resource_id = resource_id
        self.permission_id = permission_id

    @property
    def role_id(self):
        """Gets the role_id of this RoleResourcePermissionCreate.  # noqa: E501


        :return: The role_id of this RoleResourcePermissionCreate.  # noqa: E501
        :rtype: int
        """
        return self._role_id

    @role_id.setter
    def role_id(self, role_id):
        """Sets the role_id of this RoleResourcePermissionCreate.


        :param role_id: The role_id of this RoleResourcePermissionCreate.  # noqa: E501
        :type: int
        """
        if role_id is None:
            raise ValueError("Invalid value for `role_id`, must not be `None`")  # noqa: E501

        self._role_id = role_id

    @property
    def resource_id(self):
        """Gets the resource_id of this RoleResourcePermissionCreate.  # noqa: E501


        :return: The resource_id of this RoleResourcePermissionCreate.  # noqa: E501
        :rtype: int
        """
        return self._resource_id

    @resource_id.setter
    def resource_id(self, resource_id):
        """Sets the resource_id of this RoleResourcePermissionCreate.


        :param resource_id: The resource_id of this RoleResourcePermissionCreate.  # noqa: E501
        :type: int
        """
        if resource_id is None:
            raise ValueError("Invalid value for `resource_id`, must not be `None`")  # noqa: E501

        self._resource_id = resource_id

    @property
    def permission_id(self):
        """Gets the permission_id of this RoleResourcePermissionCreate.  # noqa: E501


        :return: The permission_id of this RoleResourcePermissionCreate.  # noqa: E501
        :rtype: int
        """
        return self._permission_id

    @permission_id.setter
    def permission_id(self, permission_id):
        """Sets the permission_id of this RoleResourcePermissionCreate.


        :param permission_id: The permission_id of this RoleResourcePermissionCreate.  # noqa: E501
        :type: int
        """
        if permission_id is None:
            raise ValueError("Invalid value for `permission_id`, must not be `None`")  # noqa: E501

        self._permission_id = permission_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RoleResourcePermissionCreate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
