swagger: '2.0'

schemes:
  - http

securityDefinitions:
  basic:
    type: basic
  APIKeyHeader:
    type: apiKey
    in: header
    name: X-API-Key

security:
  - APIKeyHeader: []

host: 'localhost:8000'

info:
  description: ''
  title: Authentication API
  version: ''

basePath: /api/v1

parameters:
  optional_limit:
    description: An optional query parameter to limit the number of results returned.
    in: query
    name: limit
    required: false
    type: integer
    minimum: 1
    maximum: 100
    default: 20
  optional_offset:
    description: >-
      An optional query parameter specifying the offset in the result set to
      start from.
    in: query
    name: offset
    required: false
    type: integer
    default: 0
    minimum: 0
  client_id:
    description: A UUID value identifying the client
    in: path
    name: client_id
    required: true
    type: string
    format: uuid
  user_id:
    description: A unique integer value identifying the user.
    in: path
    name: user_id
    required: true
    type: string
    format: uuid

paths:
  /client/:
    get:
      operationId: client_list
      parameters:
        - $ref: '#/parameters/optional_offset'
        - $ref: '#/parameters/optional_limit'
      responses:
        '200':
          description: ''
      tags:
        - oidc_provider

  /client/{client_id}/:
    parameters:
      - $ref: '#/parameters/client_id'
    delete:
      operationId: client_delete
      responses:
        '204':
          description: ''
      tags:
        - oidc_provider
    get:
      operationId: client_read
      responses:
        '200':
          description: ''
      tags:
        - oidc_provider
    patch:
      consumes:
        - application/json
      operationId: client_partial_update
      parameters:
        - in: body
          name: data
          schema:
            properties:
              _post_logout_redirect_uris:
                description: Enter each URI on a new line.
                type: string
              _redirect_uris:
                description: Enter each URI on a new line.
                type: string
              client_id:
                description: ''
                type: string
              client_secret:
                description: ''
                type: string
              client_type:
                description: >-
                  <b>Confidential</b> clients are capable of maintaining the
                  confidentiality of their credentials. <b>Public</b> clients
                  are incapable.
                type: string
              contact_email:
                description: ''
                type: string
              jwt_alg:
                description: Algorithm used to encode ID Tokens.
                type: string
              logo:
                description: ''
                type: string
              name:
                description: ''
                type: string
              require_consent:
                description: 'If disabled, the Server will NEVER ask the user for consent.'
                type: boolean
              response_type:
                description: ''
                type: string
              reuse_consent:
                description: >-
                  If enabled, the Server will save the user consent given to a
                  specific client, so that user won't be prompted for the same
                  authorization multiple times.
                type: boolean
              terms_url:
                description: External reference to the privacy policy of the client.
                type: string
              website_url:
                description: ''
                type: string
            type: object
      responses:
        '200':
          description: ''
      tags:
        - oidc_provider
    put:
      consumes:
        - application/json
      operationId: client_update
      parameters:
        - in: body
          name: data
          schema:
            properties:
              _post_logout_redirect_uris:
                description: Enter each URI on a new line.
                type: string
              _redirect_uris:
                description: Enter each URI on a new line.
                type: string
              client_id:
                description: ''
                type: string
              client_secret:
                description: ''
                type: string
              client_type:
                description: >-
                  <b>Confidential</b> clients are capable of maintaining the
                  confidentiality of their credentials. <b>Public</b> clients
                  are incapable.
                type: string
              contact_email:
                description: ''
                type: string
              jwt_alg:
                description: Algorithm used to encode ID Tokens.
                type: string
              logo:
                description: ''
                type: string
              name:
                description: ''
                type: string
              require_consent:
                description: 'If disabled, the Server will NEVER ask the user for consent.'
                type: boolean
              response_type:
                description: ''
                type: string
              reuse_consent:
                description: >-
                  If enabled, the Server will save the user consent given to a
                  specific client, so that user won't be prompted for the same
                  authorization multiple times.
                type: boolean
              terms_url:
                description: External reference to the privacy policy of the client.
                type: string
              website_url:
                description: ''
                type: string
            required:
              - client_id
              - response_type
            type: object
      responses:
        '200':
          description: ''
      tags:
        - oidc_provider
  /user/:
    get:
      operationId: user_list
      parameters:
        - $ref: '#/parameters/optional_offset'
        - $ref: '#/parameters/optional_limit'
      responses:
        '200':
          description: ''
      tags:
        - oidc_provider
    post:
      consumes:
        - application/json
      operationId: user_create
      parameters:
        - in: body
          name: data
          schema:
            properties:
              date_joined:
                description: ''
                type: string
                format: date
              email:
                description: ''
                type: string
                format: email
              first_name:
                description: ''
                type: string
              is_active:
                description: >-
                  Designates whether this user should be treated as active.
                  Deselect this instead of deleting accounts.
                type: boolean
              last_login:
                description: ''
                type: string
              last_name:
                description: ''
                type: string
              password:
                description: ''
                type: string
              username:
                description: >-
                  Required. 150 characters or fewer. Letters, digits and
                  @/./+/-/_ only.
                type: string
            required:
              - password
              - username
            type: object
      responses:
        '201':
          description: ''
      tags:
        - oidc_provider
  '/user/{user_id}/':
    parameters:
      - $ref: '#/parameters/user_id'
    delete:
      operationId: user_delete
      responses:
        '204':
          description: ''
      tags:
        - oidc_provider
    get:
      operationId: user_read
      responses:
        '200':
          description: ''
      tags:
        - oidc_provider
    patch:
      consumes:
        - application/json
      operationId: user_partial_update
      parameters:
        - in: body
          name: data
          schema:
            properties:
              date_joined:
                description: ''
                type: string
                format: date
              email:
                description: ''
                type: string
                format: email
              first_name:
                description: ''
                type: string
              is_active:
                description: >-
                  Designates whether this user should be treated as active.
                  Deselect this instead of deleting accounts.
                type: boolean
              last_login:
                description: ''
                type: string
                format: date-time
              last_name:
                description: ''
                type: string
              password:
                description: ''
                type: string
              username:
                description: >-
                  Required. 150 characters or fewer. Letters, digits and
                  @/./+/-/_ only.
                type: string
            type: object
      responses:
        '200':
          description: ''
      tags:
        - oidc_provider
    put:
      consumes:
        - application/json
      operationId: user_update
      parameters:
        - in: body
          name: data
          schema:
            properties:
              date_joined:
                description: ''
                type: string
                format: date
              email:
                description: ''
                type: string
                format: email
              first_name:
                description: ''
                type: string
              is_active:
                description: >-
                  Designates whether this user should be treated as active.
                  Deselect this instead of deleting accounts.
                type: boolean
              last_login:
                description: ''
                type: string
                format: date-time
              last_name:
                description: ''
                type: string
              password:
                description: ''
                type: string
              username:
                description: >-
                  Required. 150 characters or fewer. Letters, digits and
                  @/./+/-/_ only.
                type: string
            required:
              - password
              - username
            type: object
      responses:
        '200':
          description: ''
      tags:
        - oidc_provider
