# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-18 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryMigrationUserStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, verbose_name='username')),
                ('pw_hash', models.CharField(max_length=128, verbose_name='password')),
                ('app_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('site_id', models.IntegerField()),
            ],
        ),
        migrations.AddIndex(
            model_name='temporarymigrationuserstore',
            index=models.Index(fields=['username', 'app_id', 'site_id'], name='user_migrat_usernam_4eb2e2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='temporarymigrationuserstore',
            unique_together=set([('username', 'site_id', 'app_id'), ('user_id', 'site_id', 'app_id')]),
        ),
    ]
