# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-16 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryMigrationUserStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, verbose_name='username')),
                ('pw_hash', models.CharField(max_length=128, verbose_name='password')),
                ('app_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('site_id', models.IntegerField()),
            ],
        ),
    ]
