# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-28 14:59
from __future__ import unicode_literals
import uuid

import django
from django.db import migrations, models
from django.contrib.auth.hashers import make_password


def migrate_answer():
    return make_password(str(uuid.uuid1()))
def migrate_question():
    return str(uuid.uuid1())

class Migration(migrations.Migration):

    dependencies = [
        ('user_migration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='temporarymigrationuserstore',
            name='user_migrat_usernam_4eb2e2_idx',
        ),
        migrations.AddField(
            model_name='temporarymigrationuserstore',
            name='answer_one',
            field=models.CharField(default=migrate_answer, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temporarymigrationuserstore',
            name='answer_two',
            field=models.CharField(default=migrate_answer, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temporarymigrationuserstore',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oidc_provider.Client', to_field='client_id'),
        ),
        migrations.AddField(
            model_name='temporarymigrationuserstore',
            name='question_one',
            field=models.CharField(default=migrate_question, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temporarymigrationuserstore',
            name='question_two',
            field=models.CharField(default=migrate_question, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='temporarymigrationuserstore',
            unique_together=set([('username', 'client'), ('user_id', 'client')]),
        ),
        migrations.AddIndex(
            model_name='temporarymigrationuserstore',
            index=models.Index(fields=['username', 'client'], name='user_migrat_usernam_c7b8d5_idx'),
        ),
        migrations.RemoveField(
            model_name='temporarymigrationuserstore',
            name='app_id',
        ),
        migrations.RemoveField(
            model_name='temporarymigrationuserstore',
            name='site_id',
        ),
    ]
