# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 10:52
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_migration', '0002_auto_20180528_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarymigrationuserstore',
            name='question_one',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='temporarymigrationuserstore',
            name='question_two',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
    ]
