# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-05 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_migration', '0003_auto_20180531_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarymigrationuserstore',
            name='answer_one',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='temporarymigrationuserstore',
            name='answer_two',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
