# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-15 13:02
from __future__ import unicode_literals

from django.db import migrations, models
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    initial = True

    run_before = [
        ('authentication_service', '0001_initial'),
    ]
    dependencies = [
    ]

    operations = [
        TrigramExtension(),
        migrations.CreateModel(
            name='DummyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryUserStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, verbose_name='username')),
                ('pw_hash', models.CharField(max_length=128, verbose_name='password')),
                ('app_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('site_id', models.IntegerField()),
            ],
        ),
    ]
