# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-15 13:02
from __future__ import unicode_literals

from django.db import migrations, models
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    initial = True

    run_before = [
        ('authentication_service', '0001_initial'),
    ]
    dependencies = [
    ]

    operations = [
        TrigramExtension(),
        migrations.CreateModel(
            name='DummyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
