# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-14 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_temporaryuserstore'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='temporaryuserstore',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='temporaryuserstore',
            name='last_login',
        ),
    ]
