# coding: utf-8

"""
    User Data API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class DeletedUser(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'username': 'str',
        'email': 'str',
        'msisdn': 'str',
        'reason': 'str',
        'created_at': 'datetime',
        'updated_at': 'datetime',
        'deleted_at': 'datetime',
        'deleter_id': 'str'
    }

    attribute_map = {
        'id': 'id',
        'username': 'username',
        'email': 'email',
        'msisdn': 'msisdn',
        'reason': 'reason',
        'created_at': 'created_at',
        'updated_at': 'updated_at',
        'deleted_at': 'deleted_at',
        'deleter_id': 'deleter_id'
    }

    def __init__(self, id=None, username=None, email=None, msisdn=None, reason=None, created_at=None, updated_at=None, deleted_at=None, deleter_id=None):  # noqa: E501
        """DeletedUser - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._username = None
        self._email = None
        self._msisdn = None
        self._reason = None
        self._created_at = None
        self._updated_at = None
        self._deleted_at = None
        self._deleter_id = None
        self.discriminator = None

        self.id = id
        self.username = username
        if email is not None:
            self.email = email
        if msisdn is not None:
            self.msisdn = msisdn
        self.reason = reason
        self.created_at = created_at
        self.updated_at = updated_at
        if deleted_at is not None:
            self.deleted_at = deleted_at
        self.deleter_id = deleter_id

    @property
    def id(self):
        """Gets the id of this DeletedUser.  # noqa: E501


        :return: The id of this DeletedUser.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this DeletedUser.


        :param id: The id of this DeletedUser.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def username(self):
        """Gets the username of this DeletedUser.  # noqa: E501


        :return: The username of this DeletedUser.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this DeletedUser.


        :param username: The username of this DeletedUser.  # noqa: E501
        :type: str
        """
        if username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")  # noqa: E501

        self._username = username

    @property
    def email(self):
        """Gets the email of this DeletedUser.  # noqa: E501


        :return: The email of this DeletedUser.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this DeletedUser.


        :param email: The email of this DeletedUser.  # noqa: E501
        :type: str
        """

        self._email = email

    @property
    def msisdn(self):
        """Gets the msisdn of this DeletedUser.  # noqa: E501


        :return: The msisdn of this DeletedUser.  # noqa: E501
        :rtype: str
        """
        return self._msisdn

    @msisdn.setter
    def msisdn(self, msisdn):
        """Sets the msisdn of this DeletedUser.


        :param msisdn: The msisdn of this DeletedUser.  # noqa: E501
        :type: str
        """

        self._msisdn = msisdn

    @property
    def reason(self):
        """Gets the reason of this DeletedUser.  # noqa: E501


        :return: The reason of this DeletedUser.  # noqa: E501
        :rtype: str
        """
        return self._reason

    @reason.setter
    def reason(self, reason):
        """Sets the reason of this DeletedUser.


        :param reason: The reason of this DeletedUser.  # noqa: E501
        :type: str
        """
        if reason is None:
            raise ValueError("Invalid value for `reason`, must not be `None`")  # noqa: E501

        self._reason = reason

    @property
    def created_at(self):
        """Gets the created_at of this DeletedUser.  # noqa: E501


        :return: The created_at of this DeletedUser.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this DeletedUser.


        :param created_at: The created_at of this DeletedUser.  # noqa: E501
        :type: datetime
        """
        if created_at is None:
            raise ValueError("Invalid value for `created_at`, must not be `None`")  # noqa: E501

        self._created_at = created_at

    @property
    def updated_at(self):
        """Gets the updated_at of this DeletedUser.  # noqa: E501


        :return: The updated_at of this DeletedUser.  # noqa: E501
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this DeletedUser.


        :param updated_at: The updated_at of this DeletedUser.  # noqa: E501
        :type: datetime
        """
        if updated_at is None:
            raise ValueError("Invalid value for `updated_at`, must not be `None`")  # noqa: E501

        self._updated_at = updated_at

    @property
    def deleted_at(self):
        """Gets the deleted_at of this DeletedUser.  # noqa: E501


        :return: The deleted_at of this DeletedUser.  # noqa: E501
        :rtype: datetime
        """
        return self._deleted_at

    @deleted_at.setter
    def deleted_at(self, deleted_at):
        """Sets the deleted_at of this DeletedUser.


        :param deleted_at: The deleted_at of this DeletedUser.  # noqa: E501
        :type: datetime
        """

        self._deleted_at = deleted_at

    @property
    def deleter_id(self):
        """Gets the deleter_id of this DeletedUser.  # noqa: E501


        :return: The deleter_id of this DeletedUser.  # noqa: E501
        :rtype: str
        """
        return self._deleter_id

    @deleter_id.setter
    def deleter_id(self, deleter_id):
        """Sets the deleter_id of this DeletedUser.


        :param deleter_id: The deleter_id of this DeletedUser.  # noqa: E501
        :type: str
        """
        if deleter_id is None:
            raise ValueError("Invalid value for `deleter_id`, must not be `None`")  # noqa: E501

        self._deleter_id = deleter_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DeletedUser):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
